version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - MONGODB_URI=mongodb://mongo:27017
      - DATABASE_NAME=salt_wallet
      - JWT_SECRET=${JWT_SECRET}
      - APP_NAME=Salt Wallet
      - SOLANA_RPC_URL=${SOLANA_RPC_URL:-https://api.mainnet-beta.solana.com}
      - SOLANA_NETWORK=${SOLANA_NETWORK:-mainnet}
    depends_on:
      - mongo
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
